// This file is generated by icon spritesheet generator

export const iconNames = [
  "list",
  "lightbulb",
  "ellipsis-vertical",
  "cloud-sync",
  "cloud-check",
  "cloud-alert",
  "clipboard-x",
  "clipboard-check",
  "bug",
] as const

export type IconName = typeof iconNames[number]
